const { ollama } = require("./embeddingService");
const { OLLAMA_HOST, OLLAMA_LLM_MODEL } = require("../config/env");

/**
 * Generates an answer from the local Ollama LLM grounded in the retrieved repository context.
 *
 * @param {string} question - The user's query.
 * @param {string} context - The assembled repository code chunks with file paths.
 * @returns {Promise<string>} The generated answer.
 */
async function generateAnswer(question, context) {
    if (!question || typeof question !== "string") {
        throw new Error("Question must be a non-empty string");
    }

    const systemPrompt = `You are a GitHub repository assistant.

Answer ONLY using the repository context provided by the user.

Rules:
- Do not use outside knowledge.
- Do not invent repository details.
- Do not invent file names, paths, functions, technologies, or code.
- If the context does not contain enough information, say: "I could not find this information in the repository."
- When mentioning a file, use the exact path provided in the context.
- When explaining implementation details, rely only on the provided code.
- Keep the answer concise and specific.
- Use Markdown formatting when useful.`;

    const userPrompt = `Context from repository:
---------------------
${context || "No relevant context found."}
---------------------

User Question: ${question}

Please answer the question based only on the context above.
If relevant, mention the specific files and code referenced.`;

    try {
        const response = await ollama.chat({
            model: OLLAMA_LLM_MODEL || "llama3.2:1b",
            messages: [
                {
                    role: "system",
                    content: systemPrompt
                },
                {
                    role: "user",
                    content: userPrompt
                }
            ],
            options: {
                temperature: 0.2,
                num_predict: 512
            },
            stream: false
        });

        if (!response || !response.message || !response.message.content) {
            throw new Error("No answer generated by Ollama LLM");
        }

        return response.message.content.trim();

    } catch (error) {
        if (
            error.code === "ECONNREFUSED" ||
            (error.message && error.message.includes("ECONNREFUSED"))
        ) {
            throw new Error(
                `Cannot connect to Ollama at ${OLLAMA_HOST}. Make sure Ollama is running.`
            );
        }

        if (
            error.status_code === 404 ||
            (error.message && error.message.includes("not found"))
        ) {
            throw new Error(
                `Ollama model "${OLLAMA_LLM_MODEL}" not found. Run 'ollama pull ${OLLAMA_LLM_MODEL}' to install it.`
            );
        }

        throw error;
    }
}

module.exports = {
    generateAnswer
};